param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
    [string]$OutputPath = (Join-Path (Resolve-Path (Join-Path $PSScriptRoot '..')).Path 'docs/supported-packages.md')
)

$ErrorActionPreference = 'Stop'

function Get-ManifestCandidates {
    param([string]$Root)

    $rootJson = Get-ChildItem -Path $Root -File -Filter '*.json' -ErrorAction SilentlyContinue
    $bucketPath = Join-Path $Root 'bucket'
    $bucketJson = @()
    if (Test-Path $bucketPath) {
        $bucketJson = Get-ChildItem -Path $bucketPath -File -Filter '*.json' -ErrorAction SilentlyContinue
    }

    return (@($rootJson) + @($bucketJson)) | Sort-Object -Property FullName -Unique
}

function Test-IsScoopManifest {
    param([pscustomobject]$Manifest)

    if ($null -eq $Manifest) { return $false }
    $hasVersion = $Manifest.PSObject.Properties.Name -contains 'version'
    if (-not $hasVersion) { return $false }

    if ($Manifest.PSObject.Properties.Name -contains 'url') { return $true }
    if (-not ($Manifest.PSObject.Properties.Name -contains 'architecture')) { return $false }

    foreach ($archProp in $Manifest.architecture.PSObject.Properties) {
        $archValue = $archProp.Value
        if ($null -eq $archValue) { continue }
        if ($archValue.PSObject.Properties.Name -contains 'url') {
            $u = $archValue.url
            if ($u -is [System.Array]) {
                if ($u.Count -gt 0) { return $true }
            } elseif (-not [string]::IsNullOrWhiteSpace([string]$u)) {
                return $true
            }
        }
    }

    return $false
}

function Get-PrimaryDownloadUrl {
    param([pscustomobject]$Manifest)

    if ($Manifest.PSObject.Properties.Name -contains 'url') {
        if ($Manifest.url -is [System.Array]) {
            foreach ($u in $Manifest.url) {
                if (-not [string]::IsNullOrWhiteSpace([string]$u)) { return [string]$u }
            }
        } elseif (-not [string]::IsNullOrWhiteSpace([string]$Manifest.url)) {
            return [string]$Manifest.url
        }
    }

    if ($Manifest.PSObject.Properties.Name -contains 'architecture') {
        foreach ($archProp in $Manifest.architecture.PSObject.Properties) {
            $archValue = $archProp.Value
            if ($null -eq $archValue) { continue }
            if ($archValue.PSObject.Properties.Name -contains 'url') {
                $u = $archValue.url
                if ($u -is [System.Array]) {
                    foreach ($entry in $u) {
                        if (-not [string]::IsNullOrWhiteSpace([string]$entry)) { return [string]$entry }
                    }
                } elseif (-not [string]::IsNullOrWhiteSpace([string]$u)) {
                    return [string]$u
                }
            }
        }
    }

    return ''
}

$items = @()
foreach ($file in Get-ManifestCandidates -Root $RepoRoot) {
    try {
        $manifest = Get-Content -Path $file.FullName -Raw | ConvertFrom-Json -ErrorAction Stop
    } catch {
        continue
    }

    if (-not (Test-IsScoopManifest -Manifest $manifest)) {
        continue
    }

    $packageName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $description = ''
    if ($manifest.PSObject.Properties.Name -contains 'description') {
        $description = [string]$manifest.description
    }

    $homepage = ''
    if ($manifest.PSObject.Properties.Name -contains 'homepage') {
        $homepage = [string]$manifest.homepage
    }

    $version = ''
    if ($manifest.PSObject.Properties.Name -contains 'version') {
        $version = [string]$manifest.version
    }

    $downloadUrl = Get-PrimaryDownloadUrl -Manifest $manifest
    $sourceRepo = ''
    if (-not [string]::IsNullOrWhiteSpace($downloadUrl) -and $downloadUrl -match '^https://github\.com/([^/]+/[^/]+)/') {
        $sourceRepo = $matches[1]
    }

    $items += [pscustomobject]@{
        Name = $packageName
        Version = $version
        Description = $description
        Homepage = $homepage
        SourceRepo = $sourceRepo
        ManifestPath = $file.FullName.Substring($RepoRoot.Length + 1).Replace('\\', '/')
    }
}

$items = $items | Sort-Object -Property Name

$lines = @()
$lines += '# Supported Scoop Packages'
$lines += ''
$lines += '> This file is auto-generated by scripts/generate-supported-packages-doc.ps1. Do not edit manually.'
$lines += ''
$lines += "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss K')"
$lines += ''

if (-not $items -or $items.Count -eq 0) {
    $lines += 'No supported Scoop manifests were detected.'
} else {
    $lines += '## Table of Contents'
    $lines += ''
    foreach ($item in $items) {
        $lines += "- [$($item.Name)](#$($item.Name.ToLowerInvariant()))"
    }
    $lines += ''

    $lines += '## Packages'
    $lines += ''
    foreach ($item in $items) {
        $lines += "### $($item.Name)"
        $lines += ''
        if (-not [string]::IsNullOrWhiteSpace($item.Description)) {
            $lines += $item.Description
            $lines += ''
        }
        $lines += "- Version: $($item.Version)"
        $lines += "- Manifest: [$($item.ManifestPath)]($($item.ManifestPath))"
        if (-not [string]::IsNullOrWhiteSpace($item.Homepage)) {
            $lines += "- Homepage: $($item.Homepage)"
        }
        if (-not [string]::IsNullOrWhiteSpace($item.SourceRepo)) {
            $lines += "- Release Source: $($item.SourceRepo)"
        }
        $lines += "- Install: scoop install $($item.Name)"
        $lines += ''
    }
}

$outputDir = Split-Path -Path $OutputPath -Parent
if (-not (Test-Path $outputDir)) {
    New-Item -Path $outputDir -ItemType Directory -Force | Out-Null
}

$lines -join "`n" | Out-File -FilePath $OutputPath -Encoding utf8
Write-Host "Generated $OutputPath with $($items.Count) package entries."
