name: Run Pester tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pester:
    name: Run Pester tests
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PowerShell modules (Pester)
        shell: pwsh
        run: |
          Install-Module Pester -Force -Scope CurrentUser -SkipPublisherCheck -ErrorAction Stop

      - name: Run tests
        shell: pwsh
        run: |
          $tests = Get-ChildItem -Path ./tests -Filter *.Tests.ps1 -Recurse
          if ($tests.Count -eq 0) { Write-Host 'No tests found'; exit 0 }
          foreach ($t in $tests) { Write-Host "Running $($t.FullName)" }
          Invoke-Pester -Script './tests/*.Tests.ps1' -EnableExit -Output Detailed

