name: Verify Scoop Manifest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify-installation:
    name: Test Scoop Installation
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Scoop
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          echo "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Add bucket and install k3d-local
        run: |
          scoop bucket add gautampachnanda101 https://github.com/gautampachnanda101/scoop-bucket
          scoop install k3d-local

      - name: Verify installation
        run: |
          Get-Command k3d-local
          k3d-local --version

      - name: Test basic functionality
        run: |
          k3d-local --help

      - name: Install cluster prerequisites
        run: |
          # Install k3d, kubectl, and helm for cluster operations
          scoop bucket add main
          scoop install k3d kubectl helm

      - name: Setup Podman (better Windows networking than Docker Desktop)
        shell: pwsh
        run: |
          Write-Host "Installing Podman for Windows..."

          # Install Podman via winget
          winget install -e --id RedHat.Podman --silent --accept-package-agreements --accept-source-agreements

          # Add Podman to PATH for this session
          $podmanPath = "C:\Program Files\RedHat\Podman"
          if (Test-Path $podmanPath) {
            $env:PATH = "$podmanPath;$env:PATH"
            echo "$podmanPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          }

          # Initialize Podman machine
          Write-Host "Initializing Podman machine..."
          podman machine init

          Write-Host "Starting Podman machine..."
          podman machine start

          # Wait for Podman to be ready
          $maxAttempts = 20
          $attempt = 0
          while ($attempt -lt $maxAttempts) {
            $attempt++
            Write-Host "Waiting for Podman to be ready (attempt $attempt/$maxAttempts)..."
            try {
              podman version 2>&1 | Out-Null
              if ($LASTEXITCODE -eq 0) {
                Write-Host "✓ Podman is ready"
                podman version
                break
              }
            } catch {
              Write-Host "Podman not ready yet: $_"
            }
            Start-Sleep -Seconds 5
          }

          if ($attempt -eq $maxAttempts) {
            Write-Error "Podman failed to start after $maxAttempts attempts"
            exit 1
          }

          # Podman machine already exposes Docker-compatible API on a named pipe
          # Configure Docker host to use Podman's named pipe
          Write-Host "Configuring Docker host to use Podman named pipe..."
          $podmanPipe = "npipe:////./pipe/podman-machine-default"
          echo "DOCKER_HOST=$podmanPipe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          $env:DOCKER_HOST = $podmanPipe

          # Verify Docker API via Podman is working
          Write-Host "Verifying Docker API compatibility via Podman..."
          docker version

          Write-Host "✓ Podman Docker API is ready!"

      - name: Test cluster creation
        shell: pwsh
        timeout-minutes: 15
        env:
          DOCKER_HOST: npipe:////./pipe/podman-machine-default
        run: |
          Write-Host "Creating k3d cluster with Podman (via Docker API on named pipe)..."
          Write-Host "DOCKER_HOST=$env:DOCKER_HOST"
          Write-Host ""
          Write-Host "Using minimal cluster config for CI (1 server, 0 agents, 10min timeout)..."

          # Create cluster with minimal config for faster CI
          k3d-local create --name test-cluster --servers 1 --agents 0 --timeout 600 --verbose

          $createExitCode = $LASTEXITCODE
          if ($createExitCode -ne 0) {
            Write-Host ""
            Write-Host "=== Cluster creation failed, checking k3d logs ==="
            Write-Host ""

            # Show k3d cluster info
            Write-Host "k3d cluster list:"
            k3d cluster list

            Write-Host ""
            Write-Host "Podman containers:"
            podman ps -a

            Write-Host ""
            Write-Host "Checking k3d logs for test-cluster nodes..."

            # Try to get logs from any existing nodes
            $containers = podman ps -a --filter "label=app=k3d" --filter "label=k3d.cluster=test-cluster" --format "{{.Names}}"
            foreach ($container in $containers) {
              Write-Host ""
              Write-Host "=== Logs for $container ==="
              podman logs $container --tail 50 2>&1 | Write-Host
            }

            Write-Error "Cluster creation failed with exit code $createExitCode"
            exit 1
          }

          Write-Host "✓ Cluster creation succeeded"
          Write-Host ""
          Write-Host "Checking cluster status..."
          k3d-local status

          # Verify cluster exists using k3d command
          Write-Host ""
          Write-Host "Listing k3d clusters..."
          $clusterList = k3d cluster list | Out-String
          Write-Host $clusterList

          if ($clusterList -match "test-cluster") {
            Write-Host "✓ Cluster test-cluster found in k3d list"
          } else {
            Write-Error "✗ Cluster test-cluster NOT found in k3d list"
            exit 1
          }

          # Wait for cluster to be fully ready with progress logging
          Write-Host ""
          Write-Host "Waiting for cluster to be ready..."
          $maxAttempts = 60
          $attempt = 0
          $ready = $false

          while ($attempt -lt $maxAttempts) {
            $attempt++
            Write-Host "Checking cluster readiness (attempt $attempt/$maxAttempts)..."

            # Show k3d node status
            if ($attempt % 10 -eq 0) {
              Write-Host ""
              Write-Host "=== Current k3d nodes status ==="
              k3d node list

              Write-Host ""
              Write-Host "=== Podman containers ==="
              podman ps --filter "label=app=k3d"
            }

            try {
              $nodes = kubectl get nodes --no-headers 2>&1
              if ($LASTEXITCODE -eq 0 -and $nodes) {
                Write-Host "✓ Cluster is ready!"
                kubectl get nodes
                kubectl get pods -A
                $ready = $true
                break
              } else {
                Write-Host "kubectl not ready yet, checking k3s logs..."

                # Get k3s logs from server node every 20 attempts
                if ($attempt % 20 -eq 0) {
                  Write-Host ""
                  Write-Host "=== k3s server logs (last 20 lines) ==="
                  podman logs k3d-test-cluster-server-0 --tail 20 2>&1 | Write-Host
                }
              }
            } catch {
              Write-Host "Cluster not ready yet: $_"
            }

            Start-Sleep -Seconds 5
          }

          if (-not $ready) {
            Write-Host ""
            Write-Host "=== Final diagnostics before failing ==="
            Write-Host ""
            Write-Host "k3d cluster list:"
            k3d cluster list

            Write-Host ""
            Write-Host "k3d node list:"
            k3d node list

            Write-Host ""
            Write-Host "Podman ps:"
            podman ps -a --filter "label=app=k3d"

            Write-Host ""
            Write-Host "k3s server logs (last 100 lines):"
            podman logs k3d-test-cluster-server-0 --tail 100 2>&1 | Write-Host

            Write-Error "✗ Cluster failed to become ready after $maxAttempts attempts ($(($maxAttempts * 5)) seconds)"
            exit 1
          }

      - name: Test cluster deletion
        if: always()
        shell: pwsh
        env:
          DOCKER_HOST: npipe:////./pipe/podman-machine-default
        run: |
          Write-Host "Deleting k3d cluster..."
          k3d-local delete --name test-cluster

          # Verify cluster is deleted
          Write-Host ""
          Write-Host "Verifying cluster deletion..."
          $clusterList = k3d cluster list | Out-String
          Write-Host $clusterList

          if ($clusterList -notmatch "test-cluster") {
            Write-Host "✓ Cluster test-cluster successfully deleted"
          } else {
            Write-Warning "Cluster test-cluster may still exist"
          }

      - name: Uninstall
        if: always()
        run: |
          scoop uninstall k3d-local
          scoop bucket rm gautampachnanda101
