name: Verify Scoop Manifest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify-installation:
    name: Test Scoop Installation
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Scoop
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          echo "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Add bucket and install k3d-local
        run: |
          scoop bucket add gautampachnanda101 https://github.com/gautampachnanda101/scoop-bucket
          scoop install k3d-local

      - name: Verify installation
        run: |
          Get-Command k3d-local
          k3d-local --version

      - name: Test basic CLI functionality
        run: |
          Write-Host "=== Testing k3d-local CLI ==="
          Write-Host ""
          Write-Host "1. Testing --help"
          k3d-local --help

          Write-Host ""
          Write-Host "2. Testing command list"
          k3d-local help

      - name: Install k3d prerequisite
        run: |
          Write-Host "Installing k3d for pass-through testing..."
          scoop bucket add main
          scoop install k3d

      - name: Test k3d pass-through command
        run: |
          Write-Host "=== Testing k3d pass-through functionality ==="
          Write-Host ""
          Write-Host "1. Test 'k3d-local k3d version'"
          k3d-local k3d version

          Write-Host ""
          Write-Host "2. Test 'k3d-local k3d --help'"
          k3d-local k3d --help | Select-Object -First 10

          Write-Host ""
          Write-Host "3. Test 'k3d-local k3d cluster list'"
          k3d-local k3d cluster list

      - name: Test k3d-local commands
        run: |
          Write-Host "=== Testing k3d-local specific commands ==="
          Write-Host ""
          Write-Host "1. Testing create --help"
          k3d-local create --help

          Write-Host ""
          Write-Host "2. Testing status command"
          k3d-local status

          Write-Host ""
          Write-Host "3. Testing delete --help"
          k3d-local delete --help

      - name: Note about full cluster testing
        if: always()
        run: |
          Write-Host ""
          Write-Host "=== Note about Cluster Testing ==="
          Write-Host ""
          Write-Host "GitHub Actions Windows runners do not support Linux containers."
          Write-Host "Full k3d cluster creation/deletion testing is performed on:"
          Write-Host "  - Linux runners (ubuntu-latest)"
          Write-Host "  - macOS runners (macos-latest)"
          Write-Host ""
          Write-Host "This is handled by the homebrew-tap verification workflow."
          Write-Host ""
          Write-Host "For Windows users, k3d requires Docker Desktop with WSL2 backend"
          Write-Host "or Linux containers mode enabled. See README for setup instructions."
          Write-Host ""

      - name: Uninstall
        if: always()
        run: |
          scoop uninstall k3d-local k3d
          scoop bucket rm gautampachnanda101 main
